steps:
  - task: VSBuild@1
    inputs:
      solution: '**\*.sln'

  - task: CopyFiles@2
    inputs:
      Contents: '**'
      TargetFolder: 

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'