pool:
  vmImage: 'vs2017-win2016'

steps:
  - task: VSBuild@1
    displayName: 'Build solution'
    inputs:
      solution: '**\*.sln'
      configuration: '$(BuildConfiguration)'

  - task: CopyFiles@2
    displayName: 'Copy files'
    inputs:
      SourceFolder: '$(agent.builddirectory)/s/bin/$(BuildConfiguration)'
      Contents: 'TestMusicAppDb.dacpac'
      TargetFolder: '$(build.artifactstagingdirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'